### ISSUE TITLE
INFO Error "Connection reset by 10.1.4.2 port 22"

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_check#44] opened 2018-03-18 16:21 UTC
I recently encounter this fucking "verbose" error...
For more context, it's a package check built on a stretch Raspbian with a jessie guest.

I had to have a look to the ssh server log, on the container then, to got any informations.
The error was
```
pchecker_lxc sshd[403]: error: Could not load host key: /etc/ssh/ssh_host_rsa_key
pchecker_lxc sshd[403]: error: Could not load host key: /etc/ssh/ssh_host_dsa_key
pchecker_lxc sshd[403]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
pchecker_lxc sshd[403]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
pchecker_lxc sshd[403]: fatal: No supported key exchange algorithms [preauth]
```
Indeed, these 4 files didn't exist on my container.
To fix that error, I had to run `sudo dpkg-reconfigure openssh-server`
```
sudo lxc-attach -n pchecker_lxc -- sudo dpkg-reconfigure openssh-server
```
And, because my container was not fully built, I had to add this command to my `lxc_build.sh`. Just before "Mise en place de la connexion ssh vers l'invité."

Let me know if this error happens again or if it's just a bad luck day for me.

**Comment by alexAubin** [comment] 2021-04-09 01:41
Closing because did not reproduce in a while i guess

**Closed by alexAubin** 2021-04-09 01:41 UTC
