### ISSUE TITLE
Abort and restart a test if a temporary failure happens.

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_check#58] opened 2019-05-11 17:33 UTC
- Common curl errors
- DNS errors
    - `Network is unreachable`
- apt errors (usually dns errors)
  - `Temporary failure resolving`
- Unexpected corrupt sources
  - `Corrupt source`

Abort the current test and restart it.

**Comment by Josue-T** [comment] 2019-05-11 19:37
Could be good to also catch the new `pip` error like [here](https://ci-apps-dev.yunohost.org/jenkins/view/josue/job/synapse_ynh%20(josue)/62/console)
I made a bug report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928767) about that because I think that it's a regression from debian.

**Comment by maniackcrudelis** [comment] 2019-05-11 19:39
> error like [here](https://ci-apps-dev.yunohost.org/jenkins/view/josue/job/synapse_ynh%20(josue)/62/console)

Anything more precise... ?
It will be easy to add any error message to catch, I'm working on it.

**Comment by Josue-T** [comment] 2019-05-11 19:42
It's a python error with a loooooooooong stack strace. And it generally finish with by:
```
Warning: yunohost.hook <lambda> - [20342.1]   File "/opt/yunohost/matrix-synapse/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
Warning: yunohost.hook <lambda> - [20342.1]     total -= 1
Warning: yunohost.hook <lambda> - [20342.1] TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
On the bug report you a full stack trace

**Comment by maniackcrudelis** [comment] 2019-05-11 19:44
Hum but how could we be sure that's an temporary error ?

**Comment by Josue-T** [comment] 2019-05-11 19:54
The problem is that if pip try to get a package and there are a timeout (because some random network problem) we get this error. Normally the timeout is managed and a new network request is made... but because of some bug in the python debian package everything crash.

To resume:
- In normal case: if a network timeout happen, a new request is made.
- Actually: if a network timeout happen, everything crash.

Note that I'm 100% sure about nothing. It's just what I understood after to pass some time to try understand why many pip install failed theses last days.

**Comment by maniackcrudelis** [comment] 2019-05-11 19:56
Ok, but I mean this error, `TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'` could be from different reasons, not just a network error.

**Comment by Josue-T** [comment] 2019-05-11 20:05
Oh yes understand your question. I think if you do some reseach on your favorit search engine, you will see that all error wich match that is liked to `urllib3`. But we can't be 100% sure. If you want to be more sure you need also catch theses lines (independantly) : 
```
timeout=timeout
...
_stacktrace=sys.exc_info()[2])
```
Here is the full stack trace (but the path to the files could be different):
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215,
in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line
353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380,
in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554,
in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line
278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in
find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in
find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in
_get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in
_get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in
get_page
    "Cache-Control": "max-age=600",
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in
request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 488, in request
    resp = self.send(prep, **send_kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 190, in resolve_redirects
    **adapter_kwargs
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 609, in send
    r = adapter.send(request, **kwargs)
  File
"/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py",
line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py",
line 423, in send
    timeout=timeout
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py",
line 315, in increment
    total -= 1
```

**Comment by maniackcrudelis** [comment] 2019-05-11 20:16
Move that to an only one grep command, and that's ok

**Comment by maniackcrudelis** [comment] 2019-05-11 20:47
Currently in testing https://github.com/YunoHost/package_check/commit/cdb66d27285d0017c27ed4fe2a12e5457652338f

**Comment by Josue-T** [comment] 2019-05-12 08:12
I'm thinking now of why not managing theses error directly in the ynh_setup_source helper. By example if we get a bad checksum, maybe we can try a new time to download the file. And if it fail a new time we fail the install.

Because having a upgrade of the package wich fail just because of temporary network error it's just really bad...

**Comment by maniackcrudelis** [comment] 2019-05-12 09:40
That's not just about that error, but for sure `ynh_setup_source` could try to download the file again if it fails a first time.

**Comment by alexAubin** [comment] 2021-04-09 01:43
Closing because ynh_setup_source is more robust, and overall we now have better strategies to avoid hitting temporary errors instead of savagely retrying things

Still a couple things to improve, but should have specific tickets for those

**Closed by alexAubin** 2021-04-09 01:43 UTC
